################################################## 
# termine_services_types.py 
# generated by ZSI.generate.wsdl2python
##################################################


import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# urn:termine
##############################

class ns0:
    targetNamespace = "urn:termine"

# end class ns0 (tns: urn:termine)
